### ISSUE TITLE
코드 리뷰 방식에 관하여

### ISSUE THREAD

**Issue by mkthefreeman** [pycon-2019-webcrawler/BackEndRepo#6]
__먼저 다음글을 참조해주세요__
https://wayhome25.github.io/git/2017/07/08/git-first-pull-request-story/

앞으로는 다음과 같은 방식으로 코드 리뷰등을 할려고 합니다.
_원래 저게 맞는거죠;;_

만약 다른 방안이 있거나 조금 더 원하는 점이 있다면 말해주세요.

**Comment by o-ozogie** [comment]
넹
